### ISSUE TITLE
مشکل در تبدیل آرایه ها

### ISSUE THREAD

**Issue by masoodvahid** [webafrooz/IranSystemConvertor#2]
در هنگام تبدیل آرایه ها به IranSystem دارای خطا است. 
به نظر می رسد در تایع ToIranSystem چیزی در یکی از حلقه ها درست عمل نمی کند. 

```
$sql = mysql_query("SELECT * FROM insurance_list WHERE id='4' ")or die (mysql_error());
	$fieldValue = mysql_fetch_array($sql);	
	// Create Database ::
		while ($fieldName = mysql_fetch_field($sql))
		{		
			if (!in_array($fieldName->name,$not_in_dbf))
			{				
				$temp_header = array("$fieldName->name",$translator[$fieldName->name]['type'],strlen($fieldValue[$fieldName->name]),0);
				$temp_value = IranSystem::ToIranSystem($fieldValue[$fieldName->name]);
				array_push($db_header,$temp_header);
				array_push($db_value,$temp_value);				
			}	
		}
		if (!dbase_create('testo.dbf', $db_header)) {
			echo "Error, can't create the database\n";
		}
		
		var_dump($db_value);
```
نتیجه بدون تبدیل به ایران سیستم : 
![first](https://user-images.githubusercontent.com/15362786/36337252-6d5d0a5e-13a7-11e8-80d6-5a683e9f182b.png)

و نتیجه بعد از تبدیل به ایران سیستم : 
![screenshot-127 0 0 1-2018-02-17-05-58-09](https://user-images.githubusercontent.com/15362786/36337256-8f76fb0e-13a7-11e8-9532-a4457f9ee08e.png)

همانطور که در تصویر مشخصه، داده ها بعد از تبدیل به ایران سیستم، انباشته میشن و به داده های قبلی اضافه میشن.

**Comment by mahmoud-eskandari** [comment]
این یک تست دستی
```
  $iran = IranSystem::ToIranSystem('ایران 98');
  echo $iran . '<br>';
  $iran = IranSystem::FromIranSystem($iran);
  echo $iran . '<br>';
  $iran = IranSystem::ToIranSystem($iran);
  echo $iran . '<br>';
  $iran = IranSystem::FromIranSystem($iran);
  echo $iran . '<br>';
  $iran = IranSystem::ToIranSystem($iran);
  echo $iran . '<br>';
  $iran = IranSystem::FromIranSystem($iran);
  echo $iran . '<br>';
  $iran = IranSystem::ToIranSystem($iran);
  echo $iran . '<br>';
```
مشکل در آخرین کامیت رفع شد
این کتابخونه dev هستش
نه یونیت تست براش نوشتم و نه ریلیزش کردم
و همچنین ازش استفاده هم نکردم


شما برای ذخیره سازی این داده ازbinary
استفاده کنید چون انکدینگش در هیچ دیتابیسی ساپورت نمیشه
